services:

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ag5bg6ad7lk
      MINIO_ROOT_PASSWORD: jgd1f2h3ldh
    command: server /data --console-address ":9001"
    ports:
      - "19000:9000"   # API
      - "19001:9001"   # Web UI
    volumes:
      - ./data/minio/data:/data

  dialog-service:
    build:
      context: ./dialog-service
      dockerfile: Dockerfile
    ports:
      - "25001:8080"
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    restart: unless-stopped

  voice-to-text-service:
    build:
      context: ./voice-to-text-service
      dockerfile: Dockerfile
    volumes:
      - ./data/vosk/model/vosk-model-ru-0.42:/opt/vosk-model
    #      - ./data/vosk/model/vosk-model-small-ru-0.22:/opt/vosk-model
    ports:
      - "25002:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx10G"
    restart: unless-stopped

  bpmn-render-service:
    build: ./bpmn-render-service
    ports:
      - "25004:3000"
    restart: unless-stopped

