spring:
  application:
    name: dialog-service

render:
  format: pdf # jpeg, png, svg, pdf

client:
  voice-to-text:
    url: http://bpmn.evteev.ru:25002
  bpmn-generator:
    url: http://81.94.156.30:8000
  bpmn-render-service:
    url: http://bpmn.evteev.ru:25004

telegram:
  username: bpmn_process_bot
  token: ${TELEGRAM_TOKEN}

minio:
  ext-endpoint: http://bpmn.evteev.ru:19000
  endpoint: http://minio:9000
  access-key: ag5bg6ad7lk
  secret-key: jgd1f2h3ldh
  bucket: bpmn-files
  region: ru-central1

logging:
  level:
    root: info
    ru.evteev.bpmn.dialogservice: debug